---
- name: Update npm
  npm: name=npm state=latest

- name: Update frontend dependencies
  npm: path={{workspace}}labs-frontend state=latest

- name: Ensure grunt-cli exists
  npm: name=grunt-cli global=yes state=present

- name: Ensure bower exists
  npm: name=bower global=yes state=present

- name: Run bower
  shell: bower install chdir={{workspace}}labs-frontend

- name: Run grunt to build frontend
  shell: grunt build chdir={{workspace}}labs-frontend

