---
- name: Attempt to install compass
  gem: name=compass state=present

- name: Update npm
  npm: name=npm state=latest global=yes

- name: Update frontend dependencies
  npm: path={{workspace}}labs-frontend state=latest

- name: Ensure grunt-cli exists
  npm: name=grunt-cli global=yes state=present

- name: Ensure bower exists
  npm: name=bower global=yes state=present
  sudo: true


- name: Run bower
  shell: bower install chdir={{workspace}}labs-frontend --allow-root
  sudo: true

- name: Run grunt to build frontend
  shell: grunt build chdir={{workspace}}labs-frontend

