---
language: python
python: "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install php -qq
  - touch test.yml
  - echo "localhost ansible_connection=local" >> test.yml

install:
  # Install ansible
  - pip install ansible

script:
  # Check the role/playbooks syntax
  - ansible-playbook -i test.yml ansible/site.yml