---
- name: Add recent PHP
  shell: yes | add-apt-repository ppa:ondrej/php5

- name: Install PHP
  apt: name=php5-cli state=present update_cache=yes

- name: Install NPM
  apt: name=npm state=present