---
- hosts: all

  vars:
    - xz_args: "--fast"
    - artifact_name_suffix_command: 'echo "dev"'
    - workspace: /home/vagrant/assembler/workspace/
    - dist: /home/vagrant/assembler/workspace/

    - repos:
      - labs-json-api
      - labs-frontend

  roles:
   - { role: travis, when: ansible_os_family == 'Debian' }
   - { role: setup }
   - { role: local }
   - { role: example }
   - { role: api }
   - { role: frontend }
   - { role: clean }
