---
- hosts: all

  vars:
    - artifact_name_suffix_command: 'date +"%Y%m%d-%H%M"'
    - lzma_args: "--best --extreme"
    - workspace: $TRAVIS_BUILD_DIR/workspace/
    - dist: $TRAVIS_BUILD_DIR/dist/

    - repos:
      - labs-json-api
      - labs-frontend

  roles:
   - { role: travis, when: ansible_os_family == 'Debian' }
   - { role: setup }
   - { role: github }
   - { role: example }
   - { role: api }
   - { role: frontend }
   - { role: clean }
