---
- name: Ensure s3 directory exists
  file: path={{workspace}}s3 state=directory

- name: Compresss contents of dist directory into an S3 staging area
  shell: tar -zcvf {{workspace}}s3/assembled.tar.gz * chdir={{dist}}